apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: usr2mjajg-go
  janus-idp.io/tekton: usr2mjajg-go
  backstage.io/kubernetes-id: usr2mjajg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: usr2mjajg-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
