apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: usr2mjajg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: usr2mjajg-go 
  name: usr2mjajg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: usr2mjajg-go 
