apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: usr2mjajg-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:d8737fe7345a6c191ad5ec5fdf0d480f8d3e6e35@sha256:a68a77eeb81938c5c853a14632d066592ba4926bd08912d550c4748bb24263d5
          name: container-image
